name: skybyn
description: "A Social Network."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  agora_rtc_engine: ^6.3.2
  web_socket_channel: ^3.0.0
  http: ^1.6.0
  provider: ^6.1.2
  shared_preferences: ^2.5.4
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.3.0
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.5.0
  rxdart: ^0.28.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  device_info_plus: ^12.3.0
  package_info_plus: ^8.3.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  asn1lib: ^1.5.3
  http_parser: ^4.0.2
  translator: ^1.0.0
  flutter_launcher_icons: ^0.14.4
  local_auth: ^3.0.0
  mobile_scanner: ^7.1.3
  share_plus: ^12.0.1
  photo_view: ^0.15.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^7.0.0
  app_links: ^7.0.0
  get_it: ^9.2.0
  sdp_transform: ^0.3.2
  path: ^1.9.0
  logging: ^1.2.0
  collection: ^1.18.0
  flutter_webrtc: ^1.2.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_database: ^12.1.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  open_file: ^3.5.3
  url_launcher: ^6.2.5
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  workmanager: ^0.9.0+3
  flutter_secure_storage: ^9.0.0
  flutter_phoenix: ^1.1.0
  timeago: ^3.2.2
  font_awesome_flutter: ^10.7.0
  video_player: ^2.8.2
  youtube_player_flutter: ^9.1.0
  webview_flutter: ^4.4.2
  record: ^5.2.1
  just_audio: ^0.9.46
  sqflite: ^2.3.3+2
  sqflite_common_ffi: ^2.3.3
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  record_linux: ^1.2.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
